### ISSUE TITLE
Scanner Implant Crash

### ISSUE THREAD

**Issue by LatentDesire** [Minebot17/ExtremeEnergy#6]
Tried activating the level three implant and it crashed my game. Said this.

[10:12:57] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:57] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:57] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:57] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:57] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:57] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:58] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:12:59] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
[10:13:00] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[10:13:00] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre render
[10:13:00] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation

Also before this, I noticed this in the logs.

[09:17:29] [main/ERROR] [FML]: Coremod HookRegister: Unable to class load the plugin ru.minebot.extreme_energy.hook.HookRegister
java.lang.ClassNotFoundException: ru.minebot.extreme_energy.hook.HookRegister
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by LatentDesire** [comment]
I hope this is resolved soon, I rather like the concepts found in this mod. Hope you continue with developing this.
